apiVersion: 1

datasources:
  - name: BigQuery - Gold
    type: google-bigquery-datasource
    access: proxy
    jsonData:
      authenticationType: jwt
      clientEmail: ${BQ_CLIENT_EMAIL}
      defaultProject: ${BQ_PROJECT}
      processingLocation: us-central1
    secureJsonData:
      privateKey: ${BQ_PRIVATE_KEY}
    editable: true
