apiVersion: 1

datasources:
  - name: PostgreSQL - Monitoring
    type: postgres
    access: proxy
    url: ${PG_HOST}:${PG_PORT}
    user: ${PG_USER}
    database: ${PG_DBNAME}
    secureJsonData:
      password: ${PG_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    editable: true

  - name: Kafka - Monitoring
    type: kafka
    access: proxy
    url: ${KAFKA_BROKER}
    jsonData:
      useSchemaRegistry: false
    editable: true
