apiVersion: v1
kind: ConfigMap
metadata:
  name: config-se-ingest-idx-v1
data:        
  config.ini: |
    [postgresql]
    username = savineekonomi
    password = s4v1ne@Ek0nOm!
    host = 192.168.24.54
    dbname = savine_ekonomi

    [kafka]
    topic = monitoring_sidatuk
    boostrap_servers = kafka01.prod.bt:9092,kafka02.prod.bt:9092,kafka03.prod.bt:9092,kafka04.prod.bt:9092

    [MongoDB]
    mongoo_uri = mongodb://sniff:5n1ff%2540m0ng90@192.168.20.191:27017/?authSource=scrapper-engineer
    database = scrapper-engineer

    [RabbitMQ]
    host= 192.168.20.105
    port= 5672
    user= dev
    password= rahasia2020
    vHost= /dev
  
