apiVersion: v1
kind: ConfigMap
metadata:
  name: config-se-ingest-sidatuk-v1
data:        
  config.ini: |
    [postgresql]
    username = de_aristu
    password = 7TtnNmX55RW4
    host = 10.12.0.110
    dbname = gco-kab-dharmasraya

    [kafka]
    topic = monitoring_sidatuk
    boostrap_servers = kafka01.prod.bt:9092,kafka02.prod.bt:9092,kafka03.prod.bt:9092,kafka04.prod.bt:9092

    [MongoDB]
    mongoo_uri = mongodb://sniff:5n1ff%2540m0ng90@192.168.20.191:27017/?authSource=scrapper-engineer
    database = scrapper-engineer

    [RabbitMQ]
    host= 192.168.20.105
    port= 5672
    user= dev
    password= rahasia2020
    vHost= /dev

    [ssdb]
    host=192.168.20.175
    port=8888
    prefix_playwright=playwright-%%d
    prefix_direct=direct-%%d
    max_index=100
  
